### ISSUE TITLE
Question: Simple example

### ISSUE THREAD

**Issue by peekxc** [ofek/extensionlib#14]
This is more of a question born out of my own ignorance on Python's build internals. I would like to use extensionlib to build native extension modules interfaced with [pybind11](https://github.com/pybind/pybind11). There is a [simple example](https://github.com/pybind/python_example) of how to do this with setuptools + setup.py (and other build tools). I'm trying to figure out how to do this with extensionlib + hatch but I can't figure it out. 

1. Do I use the custom [build hook](https://hatch.pypa.io/latest/config/build/#build-hooks) to compile native extensions, or do I need to make my own build-hook plugin? 

Something like: 

```python
from hatchling.builders.hooks.plugin.interface import BuildHookInterface
class CustomHook(BuildHookInterface):
    def initialize(self, version, build_data):
        if self.target_name == 'wheel':
            ...
```

2. ...or does extensionlib scaffold these build hooks via entry-points? If I have something like this: 

```md
# pyproject.toml
...
[project.entry-points.extensions]
hatch_build = "my-pkg:ExampleExtensionModules"
```

then this should instantiate a `ExampleExtensionModules` class in a  `hatch_build.py` file, yes?  And then build things with the [build runner](https://ofek.dev/extensionlib/interface/#extension.runner.BuildRunner)? Something like: 

```python
# hatch_build.py
from extension.runner import BuildRunner
from extension.interface import ExtensionModules

class ExampleExtensionModules(ExtensionModules):
    def __init__(self, name: str, root: str, metadata: dict, config: dict):
      super().__init__(name, root, metadata, config)
      runner = BuildRunner('.', ...)
      ....

    def inputs():
      return(["src/my_pkg/ext/"]) # this stores my __init__.py + extension module source files 

    ....
```

I can't seem to parse how to connect the build script with the pyproject.toml file / with `hatch build`; `hatch build --ext` silently returns without error and without building anything in the simple example I'm trying to get going now.

**Comment by ofek** [comment]
Hey! The idea is every extension builder like pybind11 will implement this and then Hatchling will add an always-on build hook that uses https://ofek.dev/extensionlib/runners/

I haven't done that yet because I'm waiting on @henryiii to do a PoC with I think scikit-build?

**Comment by peekxc** [comment]
> I haven't done that yet because I'm waiting on @henryiii to do a PoC with I think scikit-build?

Well although a PoC w/ scikit-build would be informative, I would hope the pybind11 extension runner would be independent of scikit-build. Since I use [Meson](https://mesonbuild.com/) instead of CMake for building C++, I have no interest in scikit-build.

> The idea is every extension builder like pybind11 will implement this and then Hatchling will add an always-on build hook that uses https://ofek.dev/extensionlib/runners/

Ahh, ok this may be outside of my area of expertise. I may poke around at trying this myself but will be watching the pybind11 repo otherwise.

**Comment by henryiii** [comment]
Pybind11 is a binding tool, not a build system. Scikit-build and mesonpy are build systems, and they would support extensions. I can't speak for mesonpy, but I'll be making sure pybind11 and scikit-build work well together (in fact, as just announced at SciPy, [I'm funded to work on scikit-build over next three years](https://iscinumpy.dev/post/scikit-build-proposal/)). We've also discussed making a "simple" builder that would generate the configuration to build without hand-written CMake code - that's a bit down the road, though.

**Comment by pfmoore** [comment]
So as an outsider here whose interest is mainly "how does this fit in the packaging ecosystem?" I'm still confused over where this fits.

It sounds like @ofek is saying that this is a protocol that allows PEP 317 build backends (like hatchling), on being told that "file X is an extension managed by extension builder Y", to call Y in a standardised way to build[^1] the file X that the backend needs. Which is cool, but what is Y? It sounds like it's something like mesonpy or scikit-build - but I thought those two were PEP 517 backends? So is this for one backend to call another? Or is the expectation that we'll see a crop of a *new* sort of component, the "extension builder", which focuses on implementing a build process and exposing that functionality via extensionlib?

If enabling a new sort of "extension builder" component *is* the intention, then this sounds really cool and I look forward to seeing it bear fruit!

[^1]: This actually sounds general enough that why limit it to extensions? I could see other uses, such as a FFI tool that takes a description of a C interface and generates a Python file that wraps that interface using ctypes, with no extension involved.

**Comment by ofek** [comment]
Yes that is the intention 😄 

> I could see other uses, such as a FFI tool that takes a description of a C interface and generates a Python file that wraps that interface using ctypes, with no extension involved.

Yes, that would be valid.

> This actually sounds general enough that why limit it to extensions?

I think generalizing build hooks should be a separate endeavor.

**Comment by henryiii** [comment]
> mesonpy or scikit-build - but I thought those two were PEP 517 backends

Mesonpy predates this. Scikit-build is gaining a PEP 517 backend ~~because writing another PEP 517 backend is a right of passage for anyone in packaging~~ because the proposal predates this idea & it's a simple "easy start" point for users. Though depending on how this goes, maybe we can just rely on this. I'm not against the idea.

I'm giving a slide today at SciPy where I give an imaginary example:

```toml
[build-system]
requires = ["hatchling", "scikit-build-core", "mypyc"]
build-backend = "hatchling.build"

[project]
name = "example"
version = "0.1.0"

[[extensions]]
build-backend = "scikit_build_core.extension"
src = "src1/CMakeLists.txt"

[[extensions]]
build-backend = "scikit_build_core.extension"
src = "src2/CMakeLists.txt"

[[extensions]]
build-backend = "mypyc.extension"
src = "src/*.py"
```

I was imagining it would look something like that.

**Comment by ofek** [comment]
As currently implemented it would look like:

```toml
[build-system]
requires = ["hatchling", "scikit-build-core", "mypyc"]
build-backend = "hatchling.build"

[project]
name = "example"
version = "0.1.0"

[[project.extensions.scikit_build]]
src = "src1/CMakeLists.txt"

[[project.extensions.scikit_build]]
src = "src2/CMakeLists.txt"

[[project.extensions.mypyc]]
src = "src/*.py"
```
